-- SQL (Structured Query Language): 
--     Transact-SQL (Microsoft)
--     DML (Data Manipulation Language): CRUD(Create -> INSERT, Read -> SELECT, Update -> UPDATE, Delete > Delete)
--     DDL (Data Definition Language): Create (Database, Table)
--     PL/SQL (Oracle)